name: test CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: actions/checkout@v4
      - name: Update libs
        run: npm i
      - name: Building
        run: npm run build
